### ISSUE TITLE
webhook.Newclient

### ISSUE THREAD

**Issue by KillyKicks342** [disgoorg/disgo#159]
**Describe the bug**

**Error**
The error which gets logged if there is any:
```
import "github.com/disgoorg/disgo/webhook"

client := webhook.NewClient(snowflake.ID("webhookID"), "webhookToken")

message, err := client.CreateEmbeds(discord.NewEmbedBuilder().
	SetDescription("hello world!").
	Build(),
)
```

**Expected behavior**
Send embeded webhook

**Additional context**
undefined: webhook.Newclient

**Comment by TopiSenpai** [comment]
in a recent release `webhook.NewClient` got renamed to `webhook.New`
https://github.com/disgoorg/disgo/blob/758a43d32cecea7e510d28fa2356464509070888/webhook/webhook_client_impl.go#L13

**Comment by KillyKicks342** [comment]
I tried using client.New variable with client.CreateEmbeds and I get:

invalid operation: cannot indirect discord.NewEmbedBuilder().SetDescription("hello world!").Build() (value of type discord.Embed)

**Comment by TopiSenpai** [comment]
can you show me the code?

**Comment by TopiSenpai** [comment]
this looks fine to me

can you show the exact error?

**Comment by KillyKicks342** [comment]
cannot use discord.NewEmbedBuilder().SetDescription("hello world!").Build() (value of type discord.Embed) as type []discord.Embed in argument to client.CreateEmbeds

**Comment by TopiSenpai** [comment]
you need to provide a slice of embeds here

**Comment by KillyKicks342** [comment]
Can you give me an example, I'm still confused...

**Comment by KillyKicks342** [comment]
Thankyou!

**Comment by TopiSenpai** [comment]
sure
