### ISSUE TITLE
Add "rest.retryWithDelay()" function?

### ISSUE THREAD

**Issue by breezemight** [disgoorg/disgo#168]
if my program restarts immediately after reaching the text per minute webhook limit, will disgoorg automatically wait after the restart to send the messages or will it just throw a 429 error? 

If it throws 429 error, what's the workaround?
Probably a func that can wait for a specified time between requests?

**Comment by breezemight** [comment]
Can confirm it does sometimes. Happened once today(after an immediate reboot of program aforementioned) and disgo errored out without handling it. So I added a retry logic with delay. 

Discord sends you a time to wait for with the 429. So instead of retrying back to back 10 times. Maybe waiting for few seconds would do.

**Comment by TopiSenpai** [comment]
on immediate reboot that can happen as disgo doesn't know the headers yet
I'll investigate why it didnt retry 👍🏻

**Comment by TopiSenpai** [comment]
I think I found the issue
can you retry with https://github.com/disgoorg/disgo/pull/169 ?
