### ISSUE TITLE
Channel Select Menu - Cannot Set Channel Types

### ISSUE THREAD

**Issue by stephenwilliams** [disgoorg/disgo#274]
I believe that 

https://github.com/disgoorg/disgo/blob/9b3d573a109163625b177e69243b5972025fd4ad/discord/select_menu.go#L458

and 

https://github.com/disgoorg/disgo/blob/9b3d573a109163625b177e69243b5972025fd4ad/discord/select_menu.go#L527-L530

has the wrong type and should be using discord.ChannelType instead

**Comment by caneleex** [comment]
hi, this has been fixed in https://github.com/disgoorg/disgo/commit/4547c17ccf8040be70ff54b645376bcab37dcd24 - there should be a new release coming out soon. thanks for reporting :-)
