### ISSUE TITLE
nil Member in gatewayHandlerTypingStart causes panic

### ISSUE THREAD

**Issue by jkdlgy** [disgoorg/disgo#279]
**Describe the bug**
Event [gateway.EventTypingStart](https://github.com/disgoorg/disgo/blob/master/gateway/gateway_events.go#L533) (`TYPING_START` gateway event) sometimes has non-zero `GuildID` field, yet nil `Member` field. This results in nil pointer dereference in default library handler at https://github.com/disgoorg/disgo/blob/master/handlers/typing_start_handler.go#L26 - `event.GuildID == nil` is false at this point.

**Error**
Here are the logs for panic:
```
some-bot-app-1  | panic: runtime error: invalid memory address or nil pointer dereference
some-bot-app-1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbc9d78]
some-bot-app-1  |
some-bot-app-1  | goroutine 48 [running]:
some-bot-app-1  | github.com/disgoorg/disgo/handlers.gatewayHandlerTypingStart({0x10e19f0, 0xc0000f8840}, 0x25, 0x0, {0xf9415299c442082, 0xc000455830, 0xf00804592c440be, {0x0, 0xedc2a5328, 0x16d1ca0}, ...})
some-bot-app-1  |     /go/pkg/mod/github.com/disgoorg/disgo@v0.16.6/handlers/typing_start_handler.go:26 +0x1b8
some-bot-app-1  | github.com/disgoorg/disgo/bot.(*genericGatewayEventHandler[...]).HandleGatewayEvent(0xa2?, {0x10e19f0?, 0xc0000f8840?}, 0xc00031a9d8?, 0xc00001b938?, {0x10d4db8?, 0xc000317dd0?})
some-bot-app-1  |     /go/pkg/mod/github.com/disgoorg/disgo@v0.16.6/bot/event_manager.go:105 +0xe5
some-bot-app-1  | github.com/disgoorg/disgo/bot.(*eventManagerImpl).HandleGatewayEvent(0xc00022f570, {0xc000455800, 0xc}, 0xc000035a40?, 0xc00001bbf0?, {0x10d4db8, 0xc000317dd0})
some-bot-app-1  |     /go/pkg/mod/github.com/disgoorg/disgo@v0.16.6/bot/event_manager.go:126 +0x11f
some-bot-app-1  | github.com/disgoorg/disgo/gateway.(*gatewayImpl).listen(0xc0001b9600, 0xc000036b00)
some-bot-app-1  |     /go/pkg/mod/github.com/disgoorg/disgo@v0.16.6/gateway/gateway_impl.go:419 +0x979
some-bot-app-1  | created by github.com/disgoorg/disgo/gateway.(*gatewayImpl).open
some-bot-app-1  |     /go/pkg/mod/github.com/disgoorg/disgo@v0.16.6/gateway/gateway_impl.go:137 +0x7ca
```

I've added some logging at the application level to inspect the raw payload of `TYPING_START` events by registering a handler for `events.Raw`. The code is as following (don't pay attention to naming):
```golang
func (e *EventController) OnRawUserTypingStart(event *events.Raw) {
	if event.EventType != gateway.EventTypeTypingStart {
		return
	}

	payload, err := io.ReadAll(event.Payload)
	if err != nil {
		e.logger.Debug(
			"Error while reading body of Raw event TYPING_START",
			slog.String("err", err.Error()),
		)
		return
	}

	e.logger.Debug(
		"Got Raw event TYPING_START",
		slog.String("payload", fmt.Sprintf("%q", payload)),
	)
}
```

As it turns out, the raw event payload indeed contains `guild_id` field but no `member` field. Here are the logs for the last event which caused the panic above:
```
some-bot-app-1  | time=2023-06-25T15:24:24.166Z level=DEBUG source=/build/internal/bot/handlers/controllers/events.go:80 msg="Got Raw TYPING_START event" package=app payload="\"{\\\"user_id\\\":\\\"1081004946872352958\\\",\\\"timestamp\\\":1687706664,\\\"channel_id\\\":\\\"1122545475581649026\\\",\\\"guild_id\\\":\\\"541260942126874635\\\"}\""
```
**To Reproduce**
Steps to reproduce the behavior: can't be reproduced from the application level.

**Expected behavior**
The library doesn't panic.

**Disgo Version(please complete the following information):**
Current master, `require github.com/disgoorg/disgo v0.16.6`

**Additional context**
The bug isn't a disgo's fault, the incorrect event payload comes straight from discord. I've looked up the [gateway events docs for said event](https://discord.com/developers/docs/topics/gateway-events#typing-start), they state that the member field must always be present if the event occurs in a guild, yet it is not.
Actually I've done some research and found out when this happens. I've looked up the user for the last event which caused panic, and noticed that the user is the Clyde bot. My guess is that Clyde isn't considered a member of the guild, thus the absent `member` field in event payload. This seems to be the case, as Clyde isn't displayed in guild member list and his profile can't be edited by admin.
This time Discord has broken their own API contract. I think the only thing we can do is to add an appropriate nil check in aforementioned handler. Also, I'm not sure if there will be more unforeseen issues with this Clyde bot elsewhere in the codebase.

**Comment by topi314** [comment]
Hey, thanks for the detailed bug report. Seems like we need indeed need a nil check there. For now feel free to pr that nil check if you want, else I can add one.

I'll have a look in the next days if there could be more issues with clyde, thanks!

**Comment by jkdlgy** [comment]
As for nil check, do you think we should dispatch `events.GuildMemberTypingStart` when this happens? `GuildMemberTypingStart` struct has a value, non-pointer, `Member` field, I guess the library users might be confused if we do so, as they expect this field to have a non-zero value. Otherwise we can just not emit `events.GuildMemberTypingStart`.

**Comment by topi314** [comment]
I think we should fire it regardless & just add propper docs when it will be nil

**Comment by topi314** [comment]
will keep this open until it's in a release

**Comment by topi314** [comment]
from what I can tell there should be no other cases of nil pointers due to clyde

**Comment by topi314** [comment]
fixed in https://github.com/disgoorg/disgo/releases/tag/v0.16.7
