### ISSUE TITLE
Guild ID nil on slash-commands

### ISSUE THREAD

**Issue by snekROmonoro** [disgoorg/disgo#281]
**Describe the bug**
Guild ID is nil on slash-command interactions, even if the command is ran in a guild.

**Error**
The error which gets logged if there is any:
```
ERROR recovered from panic in event listener: runtime error: invalid memory address or nil pointer dereference
stack: goroutine 170 [running]
```

**To Reproduce**
```go
func commandListener(event *events.ApplicationCommandInteractionCreate) {
	data := event.SlashCommandInteractionData()
	if data.CommandName() == "pull-members" {
		fmt.Println(data.GuildID().String())
...
```

**Expected behavior**
It's expected to not be nil when the command is ran in a guild.

**Screenshots**
-

**Disgo Version(please complete the following information):**
 Very latest (just installed package)

**Additional context**
-

**Comment by snekROmonoro** [comment]
Apparently I was supposed to use "event.GuildID()" but OKAY

**Comment by topi314** [comment]
> Apparently I was supposed to use "event.GuildID()" but OKAY

`data.GuildID` returns the guild id of the command if it wasn't registered globally
