### ISSUE TITLE
Unlicensed dependency

### ISSUE THREAD

**Issue by matthiasr** [disgoorg/disgo#329]
**Describe the bug**
[go-csync](https://github.com/sasha-s/go-csync), introduced in commit 6c253fabf95f4488eee925b4d81a09c3202b45a1, does not have an open source license. This means that by default, it is fully copyrighted, and cannot be used in open source code.

I filed sasha-s/go-csync#4 to maybe get it open sourced, but this is not guaranteed to happen, and in any case, the version _currently_ used is not open source.

**Error**
The error which gets logged if there is any:
```
This package contains unlicensed code, which by default is copyrighted to the original author. You may not use these dependencies without first obtaining a license.
```

(from [FOSSA](https://fossa.com)).

**To Reproduce**
N/A

**Expected behavior**
Open source projects can only depend on open source code.

**Screenshots**
N/A

**Disgo Version(please complete the following information):**
 - Version 0.6.0 and later

**Additional context**
[Public repositories are not automatically open source](https://opensource.guide/legal/#are-public-github-projects-open-source).

**Comment by topi314** [comment]
resolved in https://github.com/disgoorg/disgo/commit/d55469b6b64dd3c2b6237fdab15be43d5436a3da

**Comment by matthiasr** [comment]
Thank you!
