### ISSUE TITLE
Infinite connection to the voice gateway

### ISSUE THREAD

**Issue by kvizyx** [disgoorg/disgo#355]
Recently i got very confusing bug with voice manager opening connection to voice gateway (maybe it's on my side but i have no clue what's can be wrong).

In my app i have a struct with voice manager which i'm getting from constructor:

```go
type MyStruct struct {
	...
	voiceManager voice.Manager
	...
}

func Constructor(voiceManager  voice.Manager) MyStruct {
	return MyStruct{
		...
		voiceManager: voiceManager,
		...
	}
}
```

And method where i'm connecting to voice room:
```go
func (s *MyStruct) Start() error {
	voiceConn := s.voiceManager.CreateConn(s.guildID)

	if err := voiceConn.Open(context.Background(), s.channelID, true, false); err != nil {
		return fmt.Errorf("failed to connect to voice channel: %w", err)
	}

	...
}
```
This function executes on voice channel creation event and bot actually connects to the voice room but ```voiceConn.Open()``` never returns (or returns deadline error if you pass a context with timeout). What's more confusing is that after i tried to execute the same code that was in ```Start()``` right after bot initialization with ```botClient.VoiceManager()```, the ```Open()``` function didn't froze. 

After some debugging and looking to library internals i figured out that ```Open()``` gets stuck on waiting value from channel which as far as i understood from source code, waiting for "data session description" message:

```go
func (c *connImpl) handleMessage(op Opcode, data GatewayMessageData) {
	...
	case GatewayMessageDataSessionDescription:
			c.udp.SetSecretKey(d.SecretKey)
			c.openedChan <- struct{}{}
}

func (c *connImpl) Open(ctx context.Context, channelID snowflake.ID, selfMute bool, selfDeaf bool) error {
	c.config.Logger.Debug("opening voice conn")

	if err := c.voiceStateUpdateFunc(ctx, c.state.GuildID, &channelID, selfMute, selfDeaf); err != nil {
		return err
	}

	select {
	// here we stuck on waiting value from this channel :\
	case <-c.openedChan:
		return nil
	case <-ctx.Done():
		return ctx.Err()
	}
}
```

Here is what i'm getting from debug logs when voice channel creation event happens and then i'm calling ```Start()``` function which never returns even though the bot joining voice room:
```
time=2024-05-11T20:19:33.547+03:00 level=DEBUG msg="received gateway message" name=gateway shard_id=0 shard_count=1 data="{\"t\":\"CHANNEL_CREATE\",\"s\":4,\"op\":0,\"d\":{\"version\":1715447973712,\"user_limit\":0,\"type\":2,\"rtc_region\":null,\"rate_limit_per_user\":0,\"position\":68,\"permission_overwrites\":[],\"parent_id\":\"815662015619530782\",\"nsfw\":false,\"name\":\"a\",\"last_message_id\":null,\"id\":\"1238903338918088804\",\"guild_id\":\"815656071288586282\",\"flags\":0,\"bitrate\":64000}}"
time=2024-05-11T20:19:33.548+03:00 level=DEBUG msg="sending gateway command" name=gateway shard_id=0 shard_count=1 data="{\"op\":4,\"d\":{\"guild_id\":\"815656071288586282\",\"channel_id\":\"1238903338918088804\",\"self_mute\":true,\"self_deaf\":false}}"
time=2024-05-11T20:19:33.771+03:00 level=DEBUG msg="received gateway message" name=gateway shard_id=0 shard_count=1 data="{\"t\":\"VOICE_STATE_UPDATE\",\"s\":5,\"op\":0,\"d\":{\"member\":{\"user\":{\"username\":\"voicer\",\"public_flags\":0,\"id\":\"1238045323268456488\",\"global_name\":null,\"display_name\":null,\"discriminator\":\"6595\",\"clan\":null,\"bot\":true,\"avatar_decoration_data\":null,\"avatar\":null},\"roles\":[\"1238089362927779843\"],\"premium_since\":null,\"pending\":false,\"nick\":null,\"mute\":false,\"joined_at\":\"2024-05-09T11:25:06.822000+00:00\",\"flags\":0,\"deaf\":false,\"communication_disabled_until\":null,\"avatar\":null},\"user_id\":\"1238045323268456488\",\"suppress\":false,\"session_id\":\"8cf77637e2298ee225e1dc3338cae5ed\",\"self_video\":false,\"self_mute\":true,\"self_deaf\":false,\"request_to_speak_timestamp\":null,\"mute\":false,\"guild_id\":\"815656071288586282\",\"deaf\":false,\"channel_id\":\"1238903338918088804\"}}"
```

But when i'm trying to open connection right after bot initialization, everything is fine and i'm getting the same output except of 1 additional log message about voice server update:
```
time=2024-05-11T20:29:30.994+03:00 level=DEBUG msg="received gateway message" name=gateway shard_id=0 shard_count=1 data="{\"t\":\"VOICE_SERVER_UPDATE\",\"s\":5,\"op\":0,\"d\":{\"token\":\"<session-token>\",\"guild_id\":\"815656071288586282\",\"endpoint\":\"finland10006.discord.media:443\"}}"
```

I have no idea why in one case everything is fine and in another it gets stuck with the same instance of voice manager (in separate runs of course). Can anyone suggest what the problem is?

**Comment by topi314** [comment]
Discord sends 2 events when connecting voice as you can see
`VOICE_STATE_UPDATE` which informs us of the `session_id` and the `VOICE_SERVER_UPDATE` event which informs us about the actual voice server & the credentials to connect

These events are forwarded to the bot clients `Voice.Manager` in the handlers registered see [here](https://github.com/disgoorg/disgo/blob/master/handlers/voice_handlers.go)

That mean if your don't use `bot.VoiceManager()` you have to manually forward these events to the `voice.Manager`

I would recommend you just use the `voice.Manager` provided by the `bot.Client`. You can either pass the `bot.Client` or `voice.Manager` directly from there no issue

**Comment by kvizyx** [comment]
Thanks for quick comment. If I understand you correctly, I've already using the method you suggested.

This is how i'm initializing struct through constructor
```go
myStruct := Constructor(botCleint.VoiceManager())
```

**Comment by topi314** [comment]
That should do the trick yeah
Can you show some more of your code?

My guess would be you are calling open in the goroutine which also executes the events.
This would block the goroutine which reads from the websocket and therefore you will not receive the `VOICE_SERVER_UPDATE` event.

Make sure you launch goroutines for longer running code to not unnecessarily block reading new events. (This behaviour is expected and ensures you don't run into race conditions from events)

**Comment by kvizyx** [comment]
Yeah, that was reason of problem. Thank you so much!

But I still don't understand why this is happening because every time i'm handling new event i'm starting new goroutine:
```go
func ChannelCreate(manager *SessionManagert) ChannelCreateHandler {
	return func(event *events.GuildChannelCreate) {
		if event.Channel.Type() != discord.ChannelTypeGuildVoice {
			return
		}

		go func() {
			if err := manager.SpawnSession(event.GuildID, event.ChannelID); err != nil {
				log.Printf("failed to spawn session: %s", err)
			}
		}()
	}
}
```

and then in ```SpawnSession``` i call ```Start``` function that I showed earlier so i'm not doing it in the same goroutine which execute events. But when i tried spawn new goroutine for ```Start``` instead of ```SpawnSession``` everything became fine.

**Comment by kvizyx** [comment]
Yeah, that was reason of problem. Thank you so much!

But I still don't understand why this is happening because every time i'm handling new event i'm starting new goroutine:
```go
func ChannelCreate(manager *SessionManagert) ChannelCreateHandler {
	return func(event *events.GuildChannelCreate) {
		if event.Channel.Type() != discord.ChannelTypeGuildVoice {
			return
		}

		go func() {
			if err := manager.SpawnSession(event.GuildID, event.ChannelID); err != nil {
				log.Printf("failed to spawn session: %s", err)
			}
		}()
	}
}
```

and then in ```SpawnSession``` i call ```Start``` function that I showed earlier so i'm not doing it in the same goroutine which execute events. But when i tried spawn new goroutine for ```Start``` instead of ```SpawnSession``` everything became fine.
