### ISSUE TITLE
ModalSubmitInteractionCreate does not feature a way to access the underlying message

### ISSUE THREAD

**Issue by msengbusch** [disgoorg/disgo#383]
**Is your feature request related to a problem? Please describe.**
The following problem. I am building an embed editor that can edit embeds through buttons in an action bar. When pressing a button a modal will appear where you can enter title, etc. Unfortunately, I haven't found a way to access the underlying message (embed) to edit it. After going through the debug logs it seems that discord sends the information about the message like in a ComponentInteractionCreate event, but the wrapper does not make it accessible.

**Describe the solution you'd like**
Add a message field to ModalSubmitInteractionCreate.

**Describe alternatives you've considered**
- Parsing the incoming response myself, but that would make the wrapper kinda useless
- Check for other events triggering, that contain the message data, which in hindsight is not possible.

Thanks!

**Comment by topi314** [comment]
Unfortunately discord does not send us the `message` a button triggered a modal from.
As you saw in the debug logs you got the message, but that was in the button interaction and not the modal interaction.

What this means is you would need to save the message in the button interaction to some sort of state and then later access it from the modal interaction.

**Comment by topi314** [comment]
see: https://pkg.go.dev/github.com/disgoorg/disgo/discord#ComponentInteraction

**Comment by msengbusch** [comment]
Ok. Thank you! I will find some way to do it.
