### ISSUE TITLE
Sticker

### ISSUE THREAD

**Issue by TopiSenpai** [DisgoOrg/disgo#45]
https://discord.com/developers/docs/resources/sticker

https://github.com/discord/discord-api-docs/pull/3128

**Comment by arynxd** [comment]
See feature/stickers. What exactly would we add aside from the existing Stickers field? I added some utils in accordance with the select menus / buttons already

**Comment by TopiSenpai** [comment]
@arynxd can bots uplaod stickers? if yes that I guess

**Comment by Skye-31** [comment]
they can

**Comment by arynxd** [comment]
> @arynxd can bots uplaod stickers? if yes that I guess

I was waiting for the refactor so that I could add the routes & use the multi-part-form impl. Will be adding that shortly
